apiVersion: v1
kind: Service
metadata:
  name: rc-messageboard-service-service
  namespace: runtime-chick
spec:
  type: NodePort
  selector:
    app: rc
    service: messageboard-service
  ports:
    - protocol: TCP
      port: 2007
      targetPort: 2007