apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: rc-messageboard-service-virtual
  namespace: runtime-chick
spec:
  gateways:
  - rc-gateway
  hosts:
  - "*" # from header of requests for allowed to send in, can be internal or external
  http:
  - match:
    - uri:
        prefix: /messageboard-service # path matching also, rewrite exists for changing prefixes
    route:
    - destination:
        port:
          number: 2007
        host: rc-messageboard-service-service # the dns look up for where to send the traffic ( probably an internal service)