FROM node:12.18

COPY build runtimechick-messageboard-service/build/
COPY node_modules runtimechick-messageboard-service/node_modules/

CMD npm run deploy --prefix runtimechick-messageboard-service/build